maintainer        "Opscode, Inc."
maintainer_email  "cookbooks@opscode.com"
license           "Apache 2.0"
description       "Installs teamspeak and enables service"
version           "0.8"
depends           "php"
supports "ubuntu"
