maintainer        "Opscode, Inc."
maintainer_email  "cookbooks@opscode.com"
license           "Apache 2.0"
description       "Disables apparmor service on Ubuntu"
version           "0.8"
supports          "ubuntu"
