maintainer        "Opscode, Inc."
maintainer_email  "cookbooks@opscode.com"
license           "Apache 2.0"
description       "Configures apt"
long_description  "Configures#{cookbook.name}"
version           "0.7"
recipe            "apt::cacher"
recipe            "apt::proxy"
