# Generated by Chef for <%= node[:fqdn] %>

resource <%= @resource %> {
  device    <%= node['drbd']['dev'] %>;
  disk      <%= node['drbd']['disk'] %>;
  meta-disk internal;
  on <%= node.name.split('.')[0] %> {
    address   <%= node.ipaddress %>:<%= node['drbd']['port'] %>;
  }
  on <%= node['drbd']['remote_host'].split('.')[0] %> {
    address   <%= @remote_ip %>:<%= node['drbd']['port'] %>;
  }
}
