maintainer        "Opscode, Inc."
maintainer_email  "cookbooks@opscode.com"
license           "Apache 2.0"
description       "Deprecated, was used to install and configure nanite for Chef 0.8 alpha"
version           "0.8"
