maintainer        "Opscode, Inc."
maintainer_email  "cookbooks@opscode.com"
license           "Apache 2.0"
description       "Configures php"
long_description  "Configures#{cookbook.name}"
version           "0.7"
recipe            "php::module_apc"
recipe            "php::module_curl"
recipe            "php::module_fileinfo"
recipe            "php::module_fpdf"
recipe            "php::module_gd"
recipe            "php::module_ldap"
recipe            "php::module_memcache"
recipe            "php::module_mysql"
recipe            "php::module_pgsql"
recipe            "php::module_sqlite3"
recipe            "php::pear"
recipe            "php::php4"
recipe            "php::php5-cgi"
recipe            "php::php5"
